### ISSUE TITLE
Design the hifi mobile view of the authentication screens, the fetch metadata screen and it's corresponding modules

### ISSUE THREAD

**Issue by KanmaChizea** [zuri-training/fetch_metadata_team86#23]
- [x] Sign up page

- [x] Sign in page

- [x] Fetch metadata page

- [x] Fetching module

- [x] Display metadata module

**Comment by ux-feranmi** [comment]
Here's the link to the file: https://www.figma.com/file/EzjbbhuIO996B5JoImNolD
