### ISSUE TITLE
Design the hifi mobile view of the change and forget password screens, and the conversion page with its corresponding modules 

### ISSUE THREAD

**Issue by KanmaChizea** [zuri-training/fetch_metadata_team86#24]
- [x] Conversion page

- [x] Converting module

- [x] Conversion complete module

- [x] Change password page

- [x] Forgot password page

**Comment by Ogunrin** [comment]
This link contains figma hifi design for the mobile view
https://www.figma.com/file/uW8bBeZpcuwcMSI30B4yxf/Team86_FetchMetadata?node-id=17%3A2

**Comment by Ogunrin** [comment]
This link contains figma hifi design for the mobile screen view
https://www.figma.com/file/uW8bBeZpcuwcMSI30B4yxf/Team86_FetchMetadata?node-id=17%3A2
