### ISSUE TITLE
Design the hifi for the web view

### ISSUE THREAD

**Issue by KanmaChizea** [zuri-training/fetch_metadata_team86#26]

**Comment by ux-feranmi** [comment]
Find attached the link to the hi-fi web-view design

https://www.figma.com/file/uW8bBeZpcuwcMSI30B4yxf/Team86_FetchMetadata?node-id=17%3A2

**Comment by ux-feranmi** [comment]
See updated input here: https://www.figma.com/file/EzjbbhuIO996B5JoImNolD
