### ISSUE TITLE
Prepare the prototype from the hifi web designs

### ISSUE THREAD

**Issue by KanmaChizea** [zuri-training/fetch_metadata_team86#28]

**Comment by ux-feranmi** [comment]
Hello team, I made a few adjustments to the hi-fi designs regarding the dropdown features for both the profile button and the convert file page. 

PS: I suggest you complete the entire design to make the necessary adjustments cause it affects the header of most of the pages.

Thanks

**Comment by IAmDalson** [comment]
https://www.figma.com/proto/uW8bBeZpcuwcMSI30B4yxf?node-id=10%3A2

**Comment by IAmDalson** [comment]
Done by @IAmDalson and @Favourite22
