### ISSUE TITLE
Build Landing Page

### ISSUE THREAD

**Issue by KanmaChizea** [zuri-training/fetch_metadata_team86#5]
So we are making big time progress oo

**Comment by DARQ-Envoy** [comment]
I have worked on it

**Comment by DARQ-Envoy** [comment]
I have completed it

**Comment by AnuOluwapo-3C** [comment]
I am done already but since you participated in this, there is no problem..
definitely, I don`t need to push the last responsiveness part

**Comment by Adegitetaiwo** [comment]
@megalous-lab
