### ISSUE TITLE
Update the style guides and compile the components

### ISSUE THREAD

**Issue by KanmaChizea** [zuri-training/fetch_metadata_team86#53]

**Comment by ux-feranmi** [comment]
- [ ] Update Style guides
- [ ] Compile component

**Comment by ux-feranmi** [comment]
Here is the link to the style guide:
https://www.figma.com/file/EzjbbhuIO996B5JoImNolD/FETCH-METADATA-TEAM-86?node-id=2%3A2

**Comment by thisnnamdi** [comment]
https://www.figma.com/file/EzjbbhuIO996B5JoImNolD/FETCH-METADATA-TEAM-86?node-id=2%3A2

**Comment by ux-feranmi** [comment]
> https://www.figma.com/file/EzjbbhuIO996B5JoImNolD/FETCH-METADATA-TEAM-86?node-id=2%3A2

Here is the main file link
