### ISSUE TITLE
Prepare the spreadsheet containing all the members name and their individual contributions to the project

### ISSUE THREAD

**Issue by KanmaChizea** [zuri-training/fetch_metadata_team86#55]

**Comment by jblaige** [comment]
The link to the spreadsheet has been created and it contains all active members. It is posted below.


https://docs.google.com/spreadsheets/d/1_EEQq0FIuCPQhPEAi5pd1bLkSlEIKqnUZTSkowbCIzE/edit?usp=drivesdk
